# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPHPTRAVEL2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pHPTRAVEL2(self):
    # Test name: PHPTRAVEL_2
    # Step # | name | target | value
    # 1 | open |  https://phptravels.net/login | 
    self.driver.get("https://phptravels.net/login")
    time.sleep(5)
    # 2 | click | id=email | 
    #self.driver.find_element(By.ID, "email").click()
    # 3 | type | id=email | user@phptravels.com
    self.driver.find_element(By.ID, "email").send_keys("user@phptravels.com")
    # 4 | click | id=password | 
    #self.driver.find_element(By.ID, "password").click()
    # 5 | type | id=password | demouser
    self.driver.find_element(By.ID, "password").send_keys("demouser")
    # 6 | click | id=submitBTN | 
    time.sleep(3)
    self.driver.find_element(By.ID, "submitBTN").click()
    
t2 = TestPHPTRAVEL2()
t2.setup_method(None)  
t2.test_pHPTRAVEL2()
t2.teardown_method(None)
  
