# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities



# Now you can use the 'driver' object to automate Firefox


class TestPHPTRAVEL3():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()

    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pHPTRAVEL3(self):
    # Test name: PHPTRAVEL_3
    # Step # | name | target | value
    # 1 | open | https://phptravels.net/admin | 
    self.driver.get("https://phptravels.net/admin")
    # 2 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 3 | type | id=email | admin@phptravels.com
    self.driver.find_element(By.ID, "email").send_keys("admin@phptravels.com")
    # 4 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 5 | type | id=password | demoadmin
    self.driver.find_element(By.ID, "password").send_keys("demoadmin")
    # 6 | click | id=submit | 
    self.driver.find_element(By.ID, "submit").click()
    # 7 | click | linkText=Modules | 
    time.sleep(5)
    # self.driver.find_element(By.LINK_TEXT, "Modules").click()
    self.driver.find_element(By.XPATH, "(//a[normalize-space()='Modules'])[1]").click()
    time.sleep(5)
    # 8 | click | css=.modules_cars > th #checkedbox | 
    self.driver.find_element(By.CSS_SELECTOR, ".modules_cars > th #checkedbox").click()
    # 9 | click | id=dropdownUser1 | 
    self.driver.find_element(By.ID, "dropdownUser1").click()
    # 10 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    # 11 | open | https://phptravels.net/ | 
    self.driver.get("https://phptravels.net/")


  


t3 = TestPHPTRAVEL3()
t3.setup_method(None)  
t3.test_pHPTRAVEL3()
t3.teardown_method(None)


